name: build

on:
  push:
    branches:
      - master
      - dev
    tags:
      - 'v*.*.*'
    pull_request:
      branches:
        - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 

      - name: Set up Docker Buildx 
        uses: docker/setup-buildx-action@v1

      -
        name: Login to ghcr.io
        uses: docker/login-action@v1
        with: 
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build container and push to ghcr.io
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.run_number }}
